[network]
n3h_path = "/Users/connor/code/holochain/n3h"
n3h_persistence_path = "/tmp"
bootstrap_nodes = ["/ip4/192.168.1.162/tcp/55013/ipfs/QmVYyr7eg3NEZpQbigKqUrpG256MZfNU1CioeWLJNaexBe"]

[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "sandwich--------------------------------------------------------------------------AAAEqzh28L"
key_file = "holo_tester.key"

[[agents]]
id = "test_agent2"
name = "HoloTester2"
public_address = "bagel-----------------------------------------------------------------------------AAADAq0mCu"
key_file = "holo_tester.key"

[[agents]]
id = "test_agent3"
name = "HoloTester3"
public_address = "croissant-------------------------------------------------------------------------AAAEuHzxV4"
key_file = "holo_tester.key"

[[dnas]]
id = "simple_app_dna"
file = "bundle.json"
hash = "Qm328wyq38924y"


[[instances]]
id = "test-instance1"
dna = "simple_app_dna"
agent = "test_agent2"
[instances.storage]
type = "file"
path = "./tmp-storage2"


[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 8889
[[interfaces.instances]]
id = "test-instance1"


[logger]
type = "debug"
  [[logger.rules.rules]]
    pattern = "^err/"
    color = "red"
  [[logger.rules.rules]]
    pattern = "^debug/dna"
    color = "white"
  [[logger.rules.rules]]
    pattern = ".*"
